apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rolling-deploy
  labels:
    env: dev 
spec:
  replicas: 4
  selector:
    matchLabels:
      env: dev
  minReadySeconds: 5
  strategy:
          type: RollingUpdate
          rollingUpdate:
                  maxSurge: 1
                  maxUnavailable: 0
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: sampleapp 
        image: bala0923/sampleapp:25
        imagePullPolicy: Always
        ports:
        - containerPort: 80
