---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod6
    labels:
        env: dev
        version: v1
spec:
    containers:
     - name: sampleapp 
       image: bala0923/sampleapp:latest
       ports:
        - containerPort: 90
